### PR TITLE
Handle private images

### LINKED ISSUE #13: Support private registries such as ACR
Doesn't work with private registries such as Azure Container Registry.
It just says `Unable to get image data`

### PR DESCRIPTION
**Pull request by marccampbell**
This fixes #13  by using the local docker credentials

### CODE REVIEW

File: pkg/outdated/registry.go [hunk 1]
```diff
@@ -9,14 +15,58 @@ import (
...
+		}
+
+		dockerConfig := DockerConfig{}
+		if err := json.Unmarshal(data, &dockerConfig); err != nil {
+			return nil, errors.Wrap(err, "failed to parse docker config")
+		}
+
+		for host, auth := range dockerConfig.Auths {
+			useAuth := false
+			if strings.Contains(host, "index.docker.io") && hostname == "index.docker.io" {
```
Comment (divolgin) [inline pkg/outdated/registry.go]: How about just `strings.Contains(host, hostname)`.  And then you just need one if statement.  But even better is to parse the URL and get hostname from there.

File: pkg/outdated/registry.go [hunk 2]
```diff
@@ -9,14 +15,58 @@ import (
...
+
+			if useAuth {
+				decoded, err := base64.StdEncoding.DecodeString(auth.Auth)
+				if err != nil {
+					return nil, errors.Wrap(err, "failed to decode docker auth")
+				}
+
+				usernameAndPassword := strings.Split(string(decoded), ":")
+				username = usernameAndPassword[0]
+				password = usernameAndPassword[1]
```
Comment (divolgin) [inline pkg/outdated/registry.go]: this will panic if there is no `:` in decoded

File: pkg/outdated/registry.go (hunk 1 above)
Comment (marccampbell) [reply pkg/outdated/registry.go]: I'm not sure thats better. It would still work with docker.io, but if hostname is "quay.io" and the auth is for "myprivatequay.io" it would then be a false match?  the hostname for "docker.io" is a pretty special case in docker's auth file.
